### ISSUE TITLE
Cannot import name 'patterns' with Django 1.11

### ISSUE THREAD

**Issue by ParasBotadra** [arneb/django-messages#111]
I am using this module with Django 1.11 and on running the app I am getting an error which says 
"cannot import name 'patterns'" in django_messages/urls.py
I there any way this issue can get solved?

**Comment by arneb** [comment]
Did you Install with pip or easy_install? Then you got an outdated version installed. Please install the current master branch from this repository. That code should work with Django 1.11. A new release will be uploaded to PyPI after testing with Django 2.0 is finished.

**Comment by ParasBotadra** [comment]
I installed with pip. To install with the current master branch, should I directly clone the repo in the virtual environment directory of my project?
